// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3sQQmdych99OyGnvh-kCJv_RFnf3kvMw',
    appId: '1:534568987267:web:72304fde965adfa72709b6',
    messagingSenderId: '534568987267',
    projectId: 'la-polla-millonaria',
    authDomain: 'la-polla-millonaria.firebaseapp.com',
    storageBucket: 'la-polla-millonaria.firebasestorage.app',
    measurementId: 'G-N869160M7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn4cSHeCRyjFOQ-E8OYjJplbz25rkv_lE',
    appId: '1:534568987267:android:d95270992332e3862709b6',
    messagingSenderId: '534568987267',
    projectId: 'la-polla-millonaria',
    storageBucket: 'la-polla-millonaria.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1h0prmcNwMg1oKyctjhVGeewJNDADcoQ',
    appId: '1:534568987267:ios:723601d5e2ac4cee2709b6',
    messagingSenderId: '534568987267',
    projectId: 'la-polla-millonaria',
    storageBucket: 'la-polla-millonaria.firebasestorage.app',
    iosBundleId: 'com.example.laPollaMillonaria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1h0prmcNwMg1oKyctjhVGeewJNDADcoQ',
    appId: '1:534568987267:ios:723601d5e2ac4cee2709b6',
    messagingSenderId: '534568987267',
    projectId: 'la-polla-millonaria',
    storageBucket: 'la-polla-millonaria.firebasestorage.app',
    iosBundleId: 'com.example.laPollaMillonaria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3sQQmdych99OyGnvh-kCJv_RFnf3kvMw',
    appId: '1:534568987267:web:bf1a82f759f35c052709b6',
    messagingSenderId: '534568987267',
    projectId: 'la-polla-millonaria',
    authDomain: 'la-polla-millonaria.firebaseapp.com',
    storageBucket: 'la-polla-millonaria.firebasestorage.app',
    measurementId: 'G-7GNJRH1QMG',
  );
}
